<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Flecs</AssemblyName>
    <RootNamespace>Flecs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="examples/**" />
    <Compile Remove="tests/**" />
    <Compile Remove="bin/**" />
    <Compile Remove="obj/**" />
    <None Remove="examples/**" />
    <None Remove="tests/**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="tests" />
  </ItemGroup>

</Project>
